### PR TITLE
Added VPC config and fix certificate in other regions

### LINKED ISSUE #10: Invalid certificate ARN: arn:aws:acm:us-east-1:LAMBDA_ID:certificate/CERTIFICATE_ID. Certificate must be in 'eu-central-1'.
This is my serverless.yaml

```
component: express
org: orgName
app: appName
name: api
stage: prod

inputs:
  src:
    src: ./src
    hook: npm run build:prod
    dist: ./dist
  domain: api.MY_ROUTE53_DOMAIN.com
  region: eu-central-1
```

and this is the error output

```
Initializing...
Action: "deploy" - Stage: "prod" - Org: "orgName" - App: "appName" - Name: "api"
Deploying...
Deploying Express App...
Packaging Express.js application...
Unzipping /tmp/e8ygooh/source.zip...
Files unzipped into /tmp/fd7zly1...
Installing Express + AWS Lambda handler...
Installing Serverless Framework SDK...
Zipping files...
Files zipped into /tmp/iywiid5.zip...
Verifying the default IAM Role found in state exists with the name: api-rjrujf8-lambda-role...
Verifying the meta IAM Role found in state exists with the name: arn:aws:iam::LAMBDA_ID:role/api-rjrujf8-meta-role...
Verifying the AWS Lambda with the ARN: arn:aws:lambda:eu-central-1:LAMBDA_ID:function:api-rjrujf8-function:3 and Name: api-rjrujf8-function found in state exists...
"AWS Lambda function found.  Updating it's configuration and code..."
AWS Lambda version "4" published
AWS Lambda function updated with ARN: arn:aws:lambda:eu-central-1:LAMBDA_ID:function:api-rjrujf8-function:4
Verifying alias "default"...
Alias "default" found. Updating...
Alias "default" updated.
Checking for existing API with ID: rkda8gh0wl
API found. Updating API with ID: rkda8gh0wl...
Add permission to Lambda enabling API Gateway with this ARN to call it: arn:aws:execute-api:eu-central-1:LAMBDA_ID:rkda8gh0wl/*/*
API with ID "rkda8gh0wl" Updated.
Getting Route53 Hosted Zone ID for domain: MY_ROUTE53_DOMAIN
Domain hosted zone id for MY_ROUTE53_DOMAIN is Z06488292F0FY3V47RWQ2
Checking if a certificate for the MY_ROUTE53_DOMAIN domain exists
Certificate for MY_ROUTE53_DOMAIN is in a "ISSUED" status
Verifying Custom Domain exists on API Gateway: api.MY_ROUTE53_DOMAIN...
Custom Domain not found in API Gateway: api.MY_ROUTE53_DOMAIN.  Creating it...
Domain api.MY_ROUTE53_DOMAIN not found in API Gateway. Creating...

 BadRequestException: Invalid certificate ARN: arn:aws:acm:us-east-1:LAMBDA_ID:certificate/CERTIFICATION_ID. Certificate must be in 'eu-central-1'.
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)

72s » api » Invalid certificate ARN: arn:aws:acm:us-east-1:LAMBDA_ID:certificate/CERTIFICATION_ID. Certificate must be in 'eu-central-1'.
```

### LINKED ISSUE #22: Adding VPC settings to config
Hello! 

I'm trying to use this component in a VPC and since there is no settings for VPC, I have to go to my deployed Lambda and manually add it in. This is fine in the short term but it would be nice to have it built-in as a feature for this component.

Here's what I had to do manually:

- Deploy the lambda once
- Attach `AWSLambdaVPCAccessExecutionRole` to the role that is used by the lambda
- Edit VPC settings, add VPC, subnet and security groups in the lambda dashboard

Maybe there could be a new input called `vpc` and looks similar to normal serverless template?

```yml
inputs:
  vpc:
      securityGroupIds:
        - securityGroupId1
        - securityGroupId2
      subnetIds:
        - subnetId1
        - subnetId2
```

Is this something that could potentially be added in this component? Maybe there's an easier way? Happy to discuss this further. :)

### PR DESCRIPTION
**Pull request by eahefnawy**
Closes #22 
Closes #10

### CODE REVIEW

**Review by medikoo — COMMENTED** [review]
CI failed on formatting check

File: templates/express-starter/app.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 'use strict';
 
-const express = require('express');
+const express = require('express'); // eslint-disable-line
```
Comment (medikoo) [inline templates/express-starter/app.js]: We should point specific rule in disabler (as e.g. here: https://github.com/serverless-components/express/blob/fc2544d568c921fa97c7cc5b600063f56907bdba/src/serverless.js#L3 )

Otherwise we may accidentally hide important error (e.g. typo in function name)

Comment (eahefnawy) [reply templates/express-starter/app.js]: done

**Review by medikoo — APPROVED** [review]
👍
